import { Link } from 'react-router-dom'

function PrivacyPolicy() {
  const lastUpdated = 'January 19, 2026'

  const definitions = [
    { term: 'Account', description: 'A unique account created for you to access our Service or parts of our Service.' },
    { term: 'Affiliate', description: 'An entity that controls, is controlled by, or is under common control with a party (ownership of 50% or more of voting securities).' },
    { term: 'Application', description: 'Brahmakosh, the software program provided by the Company.' },
    { term: 'Company', description: 'BRAHMAKOSH DIVINE CONSULTANCY L.L.C, Office No.1004, Al Rostamani Real Estate, Al Hamriyah, Bur Dubai P.O. Box 933309 Dubai, UAE.' },
    { term: 'Cookies', description: 'Small files placed on your device containing details of your browsing history among other uses.' },
    { term: 'Country', description: 'United Arab Emirates.' },
    { term: 'Device', description: 'Any device that can access the Service such as a computer, cell phone, or digital tablet.' },
    { term: 'Personal Data', description: 'Any information that relates to an identified or identifiable individual.' },
    { term: 'Service', description: 'The Application or the Website or both.' },
    { term: 'Service Provider', description: 'Any natural or legal person who processes data on behalf of the Company.' },
    { term: 'Usage Data', description: 'Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.' },
    { term: 'Website', description: 'Brahmakosh, accessible from https://brahmakosh.com.' },
    { term: 'You', description: 'The individual accessing or using the Service, or the legal entity on whose behalf the individual is acting.' },
  ]

  const personalDataItems = [
    'Email address',
    'First name and last name',
    'Phone number',
    'Address, State, Province, ZIP/Postal code, City',
    'Usage Data',
  ]

  const devicePermissions = [
    'Information regarding your location',
    "Information from your device's phone book (contacts list)",
    "Pictures and other information from your device's camera and photo library",
  ]

  const cookieTypes = [
    {
      title: 'Necessary / Essential Cookies',
      type: 'Session Cookies',
      admin: 'Us',
      purpose:
        'Essential to provide services available through the Website and enable core features such as authentication and fraud prevention.',
    },
    {
      title: 'Cookies Policy / Notice Acceptance Cookies',
      type: 'Persistent Cookies',
      admin: 'Us',
      purpose: 'Identify if users have accepted the use of cookies on the Website.',
    },
    {
      title: 'Functionality Cookies',
      type: 'Persistent Cookies',
      admin: 'Us',
      purpose:
        'Remember choices you make when using the Website (e.g., login details or language preference) to provide a more personal experience.',
    },
  ]

  const dataUses = [
    'To provide and maintain our Service, including monitoring usage.',
    'To manage your Account and registration as a user of the Service.',
    'For the performance of a contract for products, items, or services purchased.',
    'To contact you via email, telephone, SMS, or push notifications regarding updates or informative communications.',
    'To provide you with news, special offers, and general information about similar goods, services, and events unless you opt out.',
    'To attend and manage your requests to us.',
    'For business transfers such as mergers, restructuring, or asset sales.',
    'For other purposes such as data analysis, identifying usage trends, measuring campaign effectiveness, and improving our Service.',
  ]

  const sharingCases = [
    'With Service Providers to monitor and analyze use of our Service and to contact you.',
    'For business transfers including mergers, asset sales, financing, or acquisitions.',
    'With affiliates that must honor this Privacy Policy.',
    'With business partners to offer you certain products, services, or promotions.',
    'With other users when you share personal information in public areas.',
    'With your consent for any other purpose.',
  ]

  const legalDisclosure = [
    'Comply with a legal obligation.',
    'Protect and defend the rights or property of the Company.',
    'Prevent or investigate possible wrongdoing in connection with the Service.',
    'Protect the personal safety of users of the Service or the public.',
    'Protect against legal liability.',
  ]

  return (
    <div className="bg-white">
      <div className="bg-gradient-to-r from-beige-50 to-white border-b border-beige-200">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
          <p className="text-sm text-gold-700 font-semibold uppercase tracking-wide">Privacy Policy</p>
          <h1 className="mt-3 text-3xl md:text-4xl font-bold text-gray-900">Privacy Policy</h1>
          <p className="mt-3 text-gray-700">Last updated: {lastUpdated}</p>
          <p className="mt-6 text-gray-700 leading-relaxed">
            This Privacy Policy describes our policies and procedures on the collection, use, and disclosure of your
            information when you use the Service and tells you about your privacy rights and how the law protects you.
            By using the Service, you agree to the collection and use of information in accordance with this Privacy
            Policy.
          </p>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-12">
        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-gray-900">Interpretation and Definitions</h2>
          <div className="space-y-3">
            <h3 className="text-lg font-semibold text-gray-800">Interpretation</h3>
            <p className="text-gray-700 leading-relaxed">
              Words with capitalized initial letters have meanings defined under the following conditions. These
              definitions have the same meaning regardless of whether they appear in singular or plural.
            </p>
          </div>

          <div className="space-y-3">
            <h3 className="text-lg font-semibold text-gray-800">Definitions</h3>
            <ul className="space-y-2">
              {definitions.map((item) => (
                <li key={item.term} className="text-gray-700 leading-relaxed">
                  <strong>{item.term}:</strong> {item.description}
                </li>
              ))}
            </ul>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-gray-900">Collecting and Using Your Personal Data</h2>

          <div className="space-y-3">
            <h3 className="text-lg font-semibold text-gray-800">Types of Data Collected</h3>
            <h4 className="text-base font-semibold text-gray-800">Personal Data</h4>
            <p className="text-gray-700 leading-relaxed">
              While using our Service, we may ask you to provide certain personally identifiable information that can be
              used to contact or identify you. Personally identifiable information may include, but is not limited to:
            </p>
            <ul className="list-disc list-inside space-y-1 text-gray-700">
              {personalDataItems.map((item) => (
                <li key={item}>{item}</li>
              ))}
            </ul>
          </div>

          <div className="space-y-3">
            <h4 className="text-base font-semibold text-gray-800">Usage Data</h4>
            <p className="text-gray-700 leading-relaxed">
              Usage Data is collected automatically and may include IP address, browser type and version, pages visited,
              time and date of visits, time spent on pages, unique device identifiers, and other diagnostic data. When
              accessing via mobile device, we may collect device type, unique ID, IP address, operating system, mobile
              browser type, and other diagnostic data.
            </p>
          </div>

          <div className="space-y-3">
            <h4 className="text-base font-semibold text-gray-800">Information Collected while Using the Application</h4>
            <p className="text-gray-700 leading-relaxed">
              With your prior permission, we may collect the following to provide features of our Application. You can
              enable or disable access at any time through your device settings.
            </p>
            <ul className="list-disc list-inside space-y-1 text-gray-700">
              {devicePermissions.map((item) => (
                <li key={item}>{item}</li>
              ))}
            </ul>
            <p className="text-gray-700 leading-relaxed">
              The information may be uploaded to the Company&apos;s servers and/or a Service Provider&apos;s server or
              stored on your device.
            </p>
          </div>

          <div className="space-y-3">
            <h4 className="text-base font-semibold text-gray-800">Tracking Technologies and Cookies</h4>
            <p className="text-gray-700 leading-relaxed">
              We use Cookies and similar tracking technologies (beacons, tags, and scripts) to track activity on our
              Service and store certain information. Cookies can be &quot;Persistent&quot; or &quot;Session&quot;
              Cookies.
            </p>
            <div className="space-y-4">
              {cookieTypes.map((cookie) => (
                <div key={cookie.title} className="border border-beige-200 rounded-lg p-4 bg-beige-50">
                  <p className="font-semibold text-gray-900">{cookie.title}</p>
                  <p className="text-sm text-gray-700">
                    Type: {cookie.type} | Administered by: {cookie.admin}
                  </p>
                  <p className="mt-2 text-gray-700 leading-relaxed">{cookie.purpose}</p>
                </div>
              ))}
            </div>
            <p className="text-gray-700 leading-relaxed">
              For more information about the cookies we use and your choices, please see our Cookies Policy or the
              Cookies section of this Privacy Policy.
            </p>
          </div>
        </section>

        <section className="space-y-4">
          <h3 className="text-2xl font-semibold text-gray-900">Use of Your Personal Data</h3>
          <ul className="list-disc list-inside space-y-2 text-gray-700 leading-relaxed">
            {dataUses.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>

          <p className="text-gray-700 leading-relaxed">We may share your personal information in the following situations:</p>
          <ul className="list-disc list-inside space-y-2 text-gray-700 leading-relaxed">
            {sharingCases.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>
        </section>

        <section className="space-y-4">
          <h3 className="text-2xl font-semibold text-gray-900">Retention of Your Personal Data</h3>
          <p className="text-gray-700 leading-relaxed">
            We retain Personal Data only as long as necessary for the purposes set out in this Privacy Policy, to comply
            with legal obligations, resolve disputes, and enforce agreements and policies. Usage Data is retained for
            internal analysis for shorter periods unless required for security, functionality improvements, or legal
            obligations.
          </p>
        </section>

        <section className="space-y-4">
          <h3 className="text-2xl font-semibold text-gray-900">Transfer of Your Personal Data</h3>
          <p className="text-gray-700 leading-relaxed">
            Your information may be transferred to and maintained on computers located outside your jurisdiction where
            data protection laws may differ. By submitting information, you consent to this transfer. We take reasonable
            steps to ensure data is treated securely and no transfer occurs without adequate controls.
          </p>
        </section>

        <section className="space-y-4">
          <h3 className="text-2xl font-semibold text-gray-900">Delete Your Personal Data</h3>
          <p className="text-gray-700 leading-relaxed">
            You may delete or request deletion of Personal Data we hold about you. Where available, you can delete
            certain information within the Service, or update, amend, or delete your information in account settings. You
            may also contact us for access, correction, or deletion. We may retain certain information where legally
            required or where we have a lawful basis.
          </p>
        </section>

        <section className="space-y-4">
          <h3 className="text-2xl font-semibold text-gray-900">Disclosure of Your Personal Data</h3>
          <div className="space-y-3">
            <h4 className="text-lg font-semibold text-gray-800">Business Transactions</h4>
            <p className="text-gray-700 leading-relaxed">
              If the Company is involved in a merger, acquisition, or asset sale, your Personal Data may be transferred.
              We will provide notice before your Personal Data becomes subject to a different Privacy Policy.
            </p>
          </div>

          <div className="space-y-3">
            <h4 className="text-lg font-semibold text-gray-800">Law Enforcement</h4>
            <p className="text-gray-700 leading-relaxed">
              Under certain circumstances, the Company may be required to disclose your Personal Data if required by law
              or in response to valid requests by public authorities (e.g., a court or government agency).
            </p>
          </div>

          <div className="space-y-3">
            <h4 className="text-lg font-semibold text-gray-800">Other Legal Requirements</h4>
            <p className="text-gray-700 leading-relaxed">
              The Company may disclose your Personal Data in good faith belief that such action is necessary to:
            </p>
            <ul className="list-disc list-inside space-y-1 text-gray-700">
              {legalDisclosure.map((item) => (
                <li key={item}>{item}</li>
              ))}
            </ul>
          </div>
        </section>

        <section className="space-y-4">
          <h3 className="text-2xl font-semibold text-gray-900">Security of Your Personal Data</h3>
          <p className="text-gray-700 leading-relaxed">
            We use commercially reasonable means to protect your Personal Data, but no method of transmission over the
            internet or electronic storage is 100% secure. We cannot guarantee absolute security.
          </p>
        </section>

        <section className="space-y-4">
          <h3 className="text-2xl font-semibold text-gray-900">Detailed Information on Processing</h3>
          <p className="text-gray-700 leading-relaxed">
            Service Providers we use may have access to your Personal Data. These third-party vendors collect, store,
            use, process, and transfer information about your activity on our Service in accordance with their privacy
            policies.
          </p>
          <div className="border border-beige-200 rounded-lg p-4 bg-beige-50 space-y-2">
            <p className="font-semibold text-gray-900">Google Places</p>
            <p className="text-gray-700 leading-relaxed">
              Google Places is a service that returns information about places using HTTP requests. It may collect
              information from you and your device for security purposes. Information gathered is held in accordance with
              Google&apos;s Privacy Policy.
            </p>
            <a
              className="text-gold-700 font-medium hover:underline"
              href="https://www.google.com/intl/en/policies/privacy/"
              target="_blank"
              rel="noopener noreferrer"
            >
              https://www.google.com/intl/en/policies/privacy/
            </a>
          </div>
        </section>

        <section className="space-y-4">
          <h3 className="text-2xl font-semibold text-gray-900">Children&apos;s Privacy</h3>
          <p className="text-gray-700 leading-relaxed">
            Our Service does not address anyone under 13. We do not knowingly collect personally identifiable
            information from children under 13. If you are a parent or guardian and are aware your child has provided us
            with Personal Data, please contact us so we can remove it. If consent is required by law, we may need your
            parent&apos;s consent before collecting and using that information.
          </p>
        </section>

        <section className="space-y-4">
          <h3 className="text-2xl font-semibold text-gray-900">Links to Other Websites</h3>
          <p className="text-gray-700 leading-relaxed">
            Our Service may contain links to other websites not operated by us. If you click a third-party link, you
            will be directed to that site. We strongly advise you to review the Privacy Policy of every site you visit.
            We have no control over and assume no responsibility for third-party content, privacy policies, or practices.
          </p>
        </section>

        <section className="space-y-4">
          <h3 className="text-2xl font-semibold text-gray-900">Changes to this Privacy Policy</h3>
          <p className="text-gray-700 leading-relaxed">
            We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new
            Privacy Policy on this page and, where appropriate, via email and/or a prominent notice on our Service. The
            &quot;Last updated&quot; date at the top of this Privacy Policy will be revised accordingly. You are advised
            to review this Privacy Policy periodically. Changes are effective when posted on this page.
          </p>
        </section>

        <section className="space-y-4">
          <h3 className="text-2xl font-semibold text-gray-900">Contact Us</h3>
          <p className="text-gray-700 leading-relaxed">If you have any questions about this Privacy Policy, you can contact us:</p>
          <ul className="space-y-2 text-gray-700">
            <li>
              By email:{' '}
              <a className="text-gold-700 font-medium hover:underline" href="mailto:hello@brahmakosh.com">
                hello@brahmakosh.com
              </a>
            </li>
            <li>
              By visiting this page on our website:{' '}
              <a
                className="text-gold-700 font-medium hover:underline"
                href="https://brahmakosh.com/"
                target="_blank"
                rel="noopener noreferrer"
              >
                https://brahmakosh.com/
              </a>
            </li>
          </ul>
          <div className="pt-4">
            <Link
              to="/"
              className="inline-flex items-center px-4 py-2 text-sm font-semibold text-white bg-gradient-to-r from-gold-500 to-gold-600 rounded-lg shadow-md hover:shadow-lg hover:from-gold-600 hover:to-gold-700 transition-all"
            >
              Back to Home
            </Link>
          </div>
        </section>
      </div>
    </div>
  )
}

export default PrivacyPolicy

